# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Snapgram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Snapgram

pod 'Alamofire'
pod 'GoogleMaps'
pod 'Kingfisher'
pod 'SkeletonView'
pod 'RxSwift'
pod 'FloatingPanel'
pod 'ViewAnimator'
pod 'lottie-ios'

  target 'SnapgramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SnapgramUITests' do
    # Pods for testing
  end

end
